-- AlterTable
ALTER TABLE `bookings` ADD COLUMN `discount_applied` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `promo_code_id` INTEGER NULL;

-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('BOOKING_CREATED', 'DEPOSIT_CONFIRMED', 'HANDOVER_PENDING', 'FUNDS_RELEASED', 'REFUND_ISSUED', 'REVIEW_RECEIVED', 'PROPERTY_APPROVED', 'PROPERTY_REJECTED', 'FRAUD_ALERT', 'PAYMENT_FAILED', 'TIMEOUT_WARNING', 'DISPUTE_RESOLVED', 'BOOKING_TIMEOUT', 'BOOKING_CANCELLED') NOT NULL;

-- CreateIndex
CREATE INDEX `bookings_status_timeout_at_idx` ON `bookings`(`status`, `timeout_at`);
