-- AlterTable
ALTER TABLE `bookings` MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'LOCKED', 'COMPLETED', 'REFUNDED', 'DISPUTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('BOOKING_CREATED', 'DEPOSIT_CONFIRMED', 'HANDOVER_PENDING', 'FUNDS_RELEASED', 'REFUND_ISSUED', 'REVIEW_RECEIVED', 'PROPERTY_APPROVED', 'PROPERTY_REJECTED', 'FRAUD_ALERT', 'PAYMENT_FAILED', 'TIMEOUT_WARNING', 'DISPUTE_RESOLVED', 'BOOKING_TIMEOUT', 'BOOKING_CANCELLED', 'DOCUMENT_UPLOADED', 'DOCUMENT_APPROVED', 'DOCUMENT_REJECTED', 'KYC_APPROVED', 'KYC_REJECTED') NOT NULL;
